laravel/app/routes.php
<?php

Route::get('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::get('home', array('as' => 'home.alt', 'uses' => 'HomeController@index'));
Route::get('nossas-pecas', array('as' => 'festas', 'uses' => 'FestasController@index'));
Route::get('nossas-pecas/imagem/{id}', array('as' => 'festas.show', 'uses' => 'FestasController@mostrar'));
Route::get('venda-e-locacao', array('as' => 'locacao', 'uses' => 'LocacaoController@index'));
Route::get('venda-e-locacao/imagem/{id}', array('as' => 'locacao.show', 'uses' => 'LocacaoController@mostrar'));
Route::get('oficinas', array('as' => 'enxoval', 'uses' => 'EnxovalController@index'));
Route::get('oficinas/imagem/{id}', array('as' => 'enxoval.show', 'uses' => 'EnxovalController@mostrar'));
Route::get('presentes-e-lembrancas', array('as' => 'roupinhas', 'uses' => 'RoupinhasController@index'));
Route::get('presentes-e-lembrancas/imagem/{id}', array('as' => 'roupinhas.show', 'uses' => 'RoupinhasController@mostrar'));
Route::get('empresa', array('as' => 'empresa', 'uses' => 'EmpresaController@index'));
Route::get('contato', array('as' => 'contato', 'uses' => 'ContatoController@index'));
Route::post('contato', array('as' => 'contato.enviar', 'uses' => 'ContatoController@enviar'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('empresa', 'Painel\EmpresaController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('festas', 'Painel\FestasController');
	Route::resource('locacao', 'Painel\LocacaoController');
	Route::resource('enxoval', 'Painel\EnxovalController');
	Route::resource('roupinhas', 'Painel\RoupinhasController');
//NOVASROTASDOPAINEL//
});

laravel/app/models/Festas.php
<?php

class Festas extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'festas';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

}

laravel/app/controllers/FestasController.php
<?php

use \Festas;

class FestasController extends BaseController {

	protected $layout = 'frontend.templates.index';

	public function index()
	{
		$this->layout->content = View::make('frontend.festas.index')->with('imagens', Festas::orderBy('ordem', 'ASC')->paginate(24));
	}

	public function mostrar($id){
		return View::make('frontend.fancy')->with('imagem', Festas::find($id))->with('dir', 'festas');
	}
}

laravel/app/controllers/painel/FestasController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \File, \Festas;

class FestasController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.festas.index')->with('registros', Festas::orderBy('ordem', 'ASC')->get());		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.festas.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Festas;

		$t=Date('YmdHis');
		$imagem = Thumb::make('imagem', 1600, null, 'festas/', $t);
		Thumb::make('imagem', 90, 90, 'festas/thumbs/', $t);
		if($imagem) $object->imagem = $imagem;

		$object->legenda = Input::get('legenda');

		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Foto inserida com sucesso.');
			return Redirect::route('painel.festas.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Foto!'));	

		}
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.festas.edit')->with('registro', Festas::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Festas::find($id);

		$t=Date('YmdHis');
		$imagem = Thumb::make('imagem', 1600, null, 'festas/', $t);
		Thumb::make('imagem', 90, 90, 'festas/thumbs/', $t);
		if($imagem) $object->imagem = $imagem;

		$object->legenda = Input::get('legenda');

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Foto alterada com sucesso.');
			return Redirect::route('painel.festas.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Foto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Festas::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Foto removida com sucesso.');

		return Redirect::route('painel.festas.index');
	}

}

laravel/app/views/backend/festas/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Galerias - Nossas Peças - Editar Foto
        </h2>  

		{{ Form::open( array('route' => array('painel.festas.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					@if($registro->imagem)
						Imagem Atual<br>
						<img style="max-width:200px" src="assets/images/festas/{{$registro->imagem}}"><br>
					@endif
					<label for="inputImagem">Trocar Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem">
				</div>
				
				<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" value="{{$registro->legenda}}" >
				</div>

				<button type="submit" title="Alterar" class="btn btn-success">Alterar</button>

				<a href="{{URL::route('painel.festas.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/festas/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Galerias - Nossas Peças - Adicionar Foto
        </h2>  

		<form action="{{URL::route('painel.festas.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputImagem">Imagem</label>
					<input type="file" class="form-control" id="inputImagem" name="imagem" required>
				</div>
				
				<div class="form-group">
					<label for="inputLegenda">Legenda</label>
					<input type="text" class="form-control" id="inputLegenda" name="legenda" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['legenda'] }}" @endif >
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.festas.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/festas/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Galerias - Nossas Peças <a href='{{ URL::route('painel.festas.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Foto</a>
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='festas'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Imagem</th>
				<th>Legenda</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td><img src='assets/images/festas/thumbs/{{ $registro->imagem }}' style='max-width:150px'></td>
				<td>{{ $registro->legenda }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.festas.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.festas.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop